### ISSUE TITLE
pageBuilder must not finish() at add()

### ISSUE THREAD

**Issue by sonots** [hata/embulk-filter-speedometer#1]
this is wrong > https://github.com/hata/embulk-filter-speedometer/blob/9704530b2ee912fe1ade1bce08286a76cc5fb980/src/main/java/org/embulk/filter/SpeedometerFilterPlugin.java#L114

pageBuilder should finish() at void finish(), and close() at void close().

**Comment by hata** [comment]
Thank you for pointing out the issue.
I will check it and then create a code for it.
Give time to work for it.

**Comment by hata** [comment]
Hi,

I commit the following change to the code.

a857f4e2434804289a0e5fdedbf5e807947784e4

PageBuilder.finish() is called by SpeedometerFilterPlugin.finish() and PageBuilder.close() is called by SpeedometerFilterPlugin.close().

I guess it becomes a better code than my previous code.
Thank you very much for pointing out the issue and I close this request.
Please reopen this issue if the change is not the same as what you expected.

And I also published the new gem as version 0.2.3 for this fix.
Please check the latest version in the repository of rubygems.

**Comment by sonots** [comment]
:D
