### ISSUE TITLE
Feature Request: label option.

### ISSUE THREAD

**Issue by civitaspo** [hata/embulk-filter-speedometer#7]
Hi maintainers, I have a feature request that this plugin has `label` option because in the case of using this plugin in several places, it does not know which display is which setting. Now, I'm investigating which plugin is bottle neck, and I use this plugin after each plugin in order to know slow plugin. But this version does not have clear display to distinguish which setting. So, I want `label` option. Does it make sense?

**Comment by hata** [comment]
@civitaspo Thank you very much for the request. Based on your suggestion, I tried to create my implementation to add 'label' option to support what you want to do.
The following change is good for you?

- add 'label' option (string, optional, default is null and it means no label if it is not set.)
- When label is set like label: 'foo' in config, output log becomes like {speedometer: {label: foo, active: 0, total: 222b, ...

Please let me know if you have any comments, suggestions, and so on.

**Comment by civitaspo** [comment]
Sorry for the late reply. I read your code https://github.com/hata/embulk-filter-speedometer/commit/1aa8d27e6708a77af719b9b0492453860f893f4f, and it looks good to me. This is a feature that I want. Thanx so much!

**Comment by hata** [comment]
It is ok. I can also work late :)
I merged my code and I published the latest version as the following gem.

embulk-filter-speedometer (0.3.4)

So, please try to use the latest version, 0.3.4. See README to see the example of label option. It is just set label: 'foo' as an additional option.

Please let me know if you see any issues.

**Comment by civitaspo** [comment]
Thanx a lot!
